export type GuideSection = { title: string; paragraphs: string[]; bullets?: string[] };
export type Guide = { slug: string; title: string; description: string; toolHref: string; toolLabel: string; updated: string; sections: GuideSection[] };

export const guides: Guide[] = [
  {
    slug: "como-editar-pdf", title: "Como editar um PDF sem perder o controle do documento", description: "Entenda os tipos de edição de PDF, quando alterar texto, inserir elementos, redigir dados e revisar a saída.", toolHref: "/ferramentas/editar-pdf", toolLabel: "Abrir Editar PDF", updated: "11 de agosto de 2026",
    sections: [
      { title: "PDF não funciona como um documento do Word", paragraphs: ["Um PDF guarda páginas como uma combinação de textos posicionados, imagens, vetores, fontes e objetos internos. Por isso, clicar em uma frase nem sempre significa que existe um parágrafo contínuo por trás dela. Em muitos arquivos cada palavra, linha ou caractere pode estar em um bloco separado.", "Uma edição confiável começa identificando se você precisa apenas adicionar algo, substituir conteúdo existente ou realmente remover informação sensível. Essas três tarefas exigem técnicas diferentes."], bullets: ["Inserir texto ou imagem é uma camada nova.", "Substituir texto exige preservar posição e eliminar o conteúdo antigo da área.", "Redação de dados sensíveis precisa remover a informação, não apenas cobri-la visualmente."] },
      { title: "Use o modo certo para cada mudança", paragraphs: ["No LIM PDF, o Studio é indicado para edição visual: texto, imagens, assinatura, desenho, formas, comentários, destaques, carimbos e organização de páginas. O Modo preciso é mais adequado quando a prioridade é trabalhar com blocos detectados, camadas, alinhamento e substituição sanitizada de texto existente.", "Para PDFs escaneados, primeiro execute OCR. Sem uma camada pesquisável, aquilo que parece texto para seus olhos pode ser somente uma fotografia da página."] },
      { title: "Dimensão da página também faz parte da edição", paragraphs: ["Misturar A4, Carta e páginas de scanner com tamanhos incomuns pode causar margens diferentes, impressão desalinhada e apresentações ruins em tela. Antes da entrega final, confira as dimensões e padronize quando necessário.", "Ao redimensionar, prefira o modo Ajustar para manter a proporção. Preencher pode cortar bordas e Esticar pode deformar o conteúdo; são opções úteis apenas quando esse efeito é intencional."] },
      { title: "Checklist antes de baixar", paragraphs: ["Revise visualmente todas as páginas alteradas, confirme se assinaturas e imagens não cobrem conteúdo importante e teste links ou formulários quando existirem. Para documentos sensíveis, amplie a área de redação e tente selecionar/copiar o texto após exportar para confirmar que ele realmente não permanece disponível."], bullets: ["Confira páginas e orientação.", "Teste busca de texto depois de OCR.", "Confirme que campos editáveis devem continuar editáveis.", "Use Preflight para detectar tamanhos mistos, formulários e anotações."] },
    ],
  },
  {
    slug: "ocr-pdf-escaneado", title: "OCR em PDF escaneado: como transformar imagem em texto pesquisável", description: "Saiba a diferença entre extração de texto e OCR e como melhorar a precisão em documentos digitalizados.", toolHref: "/ferramentas/ocr-pdf", toolLabel: "Executar OCR PDF", updated: "11 de agosto de 2026",
    sections: [
      { title: "Extração de texto e OCR são coisas diferentes", paragraphs: ["Um PDF digital costuma carregar caracteres reais. Nesse caso, pesquisar, selecionar ou extrair texto é relativamente direto. Já um PDF criado por scanner pode conter apenas imagens. A busca não encontra nada porque não há caracteres para localizar.", "OCR, ou reconhecimento óptico de caracteres, analisa pixels e estima quais letras, números e palavras aparecem na imagem. Depois, uma camada textual pode ser posicionada sobre a página para permitir pesquisa e cópia sem alterar a aparência original."] },
      { title: "Qualidade de entrada define boa parte da precisão", paragraphs: ["Texto nítido, alinhado e com contraste alto tende a produzir um reconhecimento melhor. Sombras de celular, páginas inclinadas, baixa resolução e fontes muito pequenas aumentam erros. Antes do OCR, a ferramenta de limpeza de digitalização pode corrigir inclinação, clarear o fundo e aumentar contraste."], bullets: ["Prefira digitalizações retas e completas.", "Evite cortes nas margens e reflexos.", "Escolha o idioma correto quando houver essa opção.", "Revise nomes próprios, códigos, valores e números de documento."] },
      { title: "PDF pesquisável não significa documento perfeitamente editável", paragraphs: ["A camada OCR é excelente para busca, indexação, acessibilidade básica e extração. Entretanto, reconstruir exatamente a tipografia e o fluxo de um documento escaneado é uma etapa diferente. Para Word, tabelas e edição fina, sempre revise a conversão depois do reconhecimento."] },
      { title: "Privacidade em OCR local", paragraphs: ["No fluxo local do LIM PDF, o navegador carrega o motor e modelos necessários e processa as páginas no dispositivo. O arquivo do usuário não precisa ser enviado ao LIM PDF para reconhecer o texto. Na primeira execução, o download do motor pode tornar o início mais lento; execuções seguintes tendem a aproveitar recursos já em cache pelo navegador."] },
    ],
  },
  {
    slug: "comprimir-pdf-sem-perder-qualidade", title: "Como comprimir PDF sem deixar texto e imagens ilegíveis", description: "Aprenda a escolher o nível de compressão adequado e a diferença entre otimização estrutural e recompressão visual.", toolHref: "/ferramentas/compactar-pdf", toolLabel: "Compactar PDF", updated: "11 de agosto de 2026",
    sections: [
      { title: "Nem todo PDF grande tem o mesmo problema", paragraphs: ["Um documento pode ficar pesado por imagens em resolução excessiva, páginas escaneadas, fontes incorporadas, objetos repetidos, formulários ou recursos internos que deixaram de ser usados. Por isso, uma única técnica de compressão não é ideal para todos os arquivos.", "Otimização estrutural tenta remover desperdício sem transformar a aparência da página em imagem. Já a recompressão visual pode reduzir muito mais o tamanho, mas sacrifica editabilidade e pode perder nitidez."] },
      { title: "Escolha a qualidade pelo destino", paragraphs: ["Para leitura em celular e envio por mensageiro, uma compressão moderada costuma ser suficiente. Para impressão, contratos com letras pequenas e documentos técnicos, preserve mais resolução. Arquivos destinados a gráfica ou arquivamento deveriam ser comparados com o original antes de substituir a versão mestre."], bullets: ["Tela: priorize tamanho menor com texto ainda legível.", "Impressão: preserve detalhes e evite rasterização agressiva.", "Arquivo mestre: mantenha uma cópia original sem compressão destrutiva."] },
      { title: "Como conferir o resultado", paragraphs: ["Abra o arquivo baixado, amplie páginas com letras pequenas e confira imagens, códigos de barras, assinaturas e gráficos. Compare o tamanho final e confirme se recursos importantes — links, formulários e camada de texto — continuam presentes quando o método escolhido deveria preservá-los."] },
    ],
  },
  {
    slug: "remover-dados-sensiveis-pdf", title: "Como remover dados sensíveis de um PDF de forma segura", description: "Entenda por que um retângulo preto não é suficiente e como revisar uma redação antes de compartilhar o documento.", toolHref: "/ferramentas/editar-pdf", toolLabel: "Abrir redação segura", updated: "11 de agosto de 2026",
    sections: [
      { title: "Cobrir visualmente não é apagar", paragraphs: ["Colocar uma forma preta sobre CPF, endereço ou informação confidencial pode esconder o texto na tela, mas o conteúdo original ainda pode existir por baixo. Em muitos PDFs é possível selecionar, copiar, pesquisar ou extrair o texto mesmo quando ele parece coberto.", "Uma redação segura precisa eliminar o conteúdo da região na saída ou reconstruir a área de forma que a informação anterior não continue acessível como objeto editável ou texto subjacente."] },
      { title: "O que redigir", paragraphs: ["Defina a área com folga suficiente para cobrir caracteres completos e elementos associados. Não se limite ao que aparece na página: metadados, comentários, anexos, campos de formulário e versões anteriores do documento também podem conter informações que você não pretende compartilhar."], bullets: ["Dados pessoais e identificadores.", "Assinaturas, números financeiros e contatos privados.", "Comentários e notas internas.", "Metadados de autor e software, quando sensíveis."] },
      { title: "Teste a saída como se você fosse o destinatário", paragraphs: ["Depois de baixar, tente buscar o termo removido, selecionar a região, copiar o conteúdo e abrir o PDF em outro leitor. Se o documento for muito sensível, mantenha a versão original separada e distribua apenas a cópia redigida. O Preflight também ajuda a lembrar anotações, formulários e metadados que ainda precisam de revisão."] },
    ],
  },
  {
    slug: "assinatura-visual-vs-digital", title: "Assinatura visual e assinatura digital em PDF: qual é a diferença?", description: "Compare a imagem de assinatura com a assinatura criptográfica PAdES e entenda quando cada uma faz sentido.", toolHref: "/ferramentas/assinatura-digital-pdf", toolLabel: "Assinatura digital PDF", updated: "11 de agosto de 2026",
    sections: [
      { title: "Uma assinatura desenhada é um elemento visual", paragraphs: ["Quando você desenha uma rubrica, digita um nome ou coloca uma imagem de assinatura sobre a página, o PDF passa a exibir aquela marca. Isso pode ser suficiente para fluxos informais, aprovações internas ou documentos em que as partes aceitam esse procedimento.", "Mas a imagem, sozinha, não prova criptograficamente quem controlava uma chave privada nem detecta alterações posteriores no arquivo."] },
      { title: "Assinatura digital usa criptografia", paragraphs: ["Uma assinatura digital PDF associa a assinatura a um certificado e a uma chave privada. O leitor compatível pode verificar se os bytes cobertos pela assinatura permanecem íntegros e qual certificado foi incluído no processo. PAdES é um conjunto de perfis e práticas para assinaturas em PDF.", "Uma implementação básica não substitui automaticamente carimbo de tempo confiável, validação de cadeia, revogação ou preservação de longo prazo. Esses recursos dependem de infraestrutura e políticas adicionais."] },
      { title: "A1, arquivo de chave e dispositivos A3", paragraphs: ["Quando certificado e chave estão disponíveis em formato que o navegador consegue usar, a assinatura pode acontecer localmente. Tokens, cartões e alguns certificados A3 dependem de drivers e interfaces nativas do sistema; uma página comum do navegador não recebe acesso irrestrito a esses dispositivos."] },
      { title: "Antes de assinar", paragraphs: ["Finalize o conteúdo primeiro. Alterações feitas depois da assinatura podem ser reportadas como modificações pelos leitores. Se um documento já contém uma assinatura digital, use um fluxo que suporte revisões incrementais para preservar assinaturas anteriores; nunca regrave silenciosamente o arquivo inteiro supondo que as assinaturas continuarão válidas."] },
    ],
  },
  {
    slug: "pdf-a-arquivamento", title: "PDF/A para arquivamento: o que é e o que significa validar de verdade", description: "Entenda a finalidade do PDF/A, por que metadados, fontes e perfis de cor importam e a diferença entre preparar e certificar.", toolHref: "/ferramentas/pdf-a", toolLabel: "Preparar PDF/A", updated: "11 de agosto de 2026",
    sections: [
      { title: "PDF/A foi pensado para preservação", paragraphs: ["O objetivo de um perfil PDF/A é reduzir dependências externas e tornar o documento mais previsível para leitura futura. A conformidade envolve regras sobre recursos permitidos, metadados, fontes, cores e outros elementos internos; não basta mudar a extensão ou adicionar uma etiqueta ao arquivo."] },
      { title: "Preparação e validação são etapas diferentes", paragraphs: ["Uma ferramenta pode normalizar metadados, achatar recursos incompatíveis e preparar o documento para um perfil como PDF/A-2B. Ainda assim, declarar conformidade normativa exige verificar todas as regras relevantes, incluindo fontes e perfis de cor quando aplicáveis.", "Por isso o LIM PDF trata a função como preparação e pré-validação quando não há evidência suficiente para afirmar certificação ISO. Essa distinção evita um arquivo parecer conforme apenas porque recebeu metadados de identificação."] },
      { title: "Fluxo recomendado", paragraphs: ["Mantenha o original, prepare uma cópia, execute o relatório de pré-validação e, quando houver exigência regulatória ou institucional, confira a saída em um validador especializado aceito pelo seu processo. Para documentos escaneados, considere OCR antes do arquivamento para facilitar pesquisa e recuperação de informação."] },
    ],
  },
];

export const guideBySlug = new Map(guides.map((guide) => [guide.slug, guide]));
