import type { AnyToolDefinition } from "@/lib/all-tools";

export type ProToolSlug =
  | "ocr-pdf"
  | "assinatura-digital-pdf"
  | "links-pdf"
  | "criar-formulario-pdf"
  | "bookmarks-pdf"
  | "comparar-pdfs"
  | "reparar-pdf"
  | "pdf-a"
  | "pdf-para-powerpoint"
  | "powerpoint-para-pdf"
  | "extrair-imagens-pdf"
  | "limpar-documento-digitalizado"
  | "otimizar-pdf-avancado"
  | "anotacoes-pdf"
  | "processamento-lote-pdf"
  | "numeracao-bates"
  | "editar-metadados-pdf";

const privacyFaq = {
  question: "O conteúdo do documento é enviado ao LIM PDF?",
  answer: "Não. O documento é processado localmente no navegador. No OCR, somente os arquivos públicos do motor e dos idiomas são baixados; as páginas do usuário não são enviadas ao provedor do OCR.",
};

export const proTools: AnyToolDefinition[] = [
  {
    slug: "ocr-pdf",
    name: "OCR PDF",
    shortDescription: "Reconheça texto em PDFs escaneados e gere uma camada pesquisável.",
    description: "Renderize cada página localmente, reconheça português, inglês e espanhol com OCR real e gere um PDF pesquisável com o texto invisível alinhado à digitalização.",
    category: "Converter de PDF",
    icon: "TextSearch",
    accent: "blue",
    accept: "application/pdf,.pdf",
    multiple: false,
    keywords: ["ocr pdf", "pdf escaneado", "reconhecer texto", "pdf pesquisável", "tesseract"],
    intro: "Transforme digitalizações e PDFs compostos apenas por imagem em documentos pesquisáveis e com texto copiável, sem enviar as páginas para o servidor do LIM PDF.",
    useCases: ["Pesquisar contratos digitalizados", "Copiar texto de documentos escaneados", "Preparar PDF para Word/Excel", "Arquivar digitalizações pesquisáveis"],
    limitations: ["O reconhecimento depende da qualidade da digitalização", "Na primeira execução o navegador baixa o motor OCR e os modelos de idioma", "Revise nomes próprios, números pequenos e imagens com baixa resolução"],
    faq: [{ question: "É OCR de verdade?", answer: "Sim. As páginas são renderizadas como imagem e processadas pelo motor Tesseract WebAssembly, com geração de uma nova camada de texto pesquisável." }, privacyFaq],
  },
  {
    slug: "assinatura-digital-pdf",
    name: "Assinatura digital PDF",
    shortDescription: "Aplique assinatura criptográfica PAdES básica com certificado e chave RSA.",
    description: "Assine o PDF com certificado X.509 e chave privada PKCS#8 RSA diretamente no navegador, usando CMS destacado e SubFilter ETSI.CAdES.detached.",
    category: "Otimizar e proteger",
    icon: "Signature",
    accent: "green",
    accept: "application/pdf,.pdf",
    multiple: false,
    keywords: ["assinatura digital pdf", "pades", "certificado digital", "x509", "cms pdf"],
    intro: "Crie uma assinatura digital criptográfica no documento. O certificado e a chave privada ficam apenas na memória do navegador durante a operação.",
    useCases: ["Assinar documentos com certificado software", "Validar integridade do PDF", "Distribuir documento assinado criptograficamente", "Aplicar assinatura PAdES básica"],
    limitations: ["Nesta versão o navegador aceita certificado X.509 PEM e chave privada RSA PKCS#8 PEM", "Certificados em token/cartão A3 dependem de integração nativa do sistema e não podem ser acessados por uma página web comum", "LTV, carimbo do tempo TSA e validação de cadeia/revogação exigem infraestrutura de confiança adicional"],
    faq: [{ question: "É diferente da assinatura desenhada?", answer: "Sim. Esta função altera criptograficamente o PDF e permite que leitores compatíveis verifiquem integridade e certificado. A assinatura visual continua disponível separadamente." }, privacyFaq],
  },
  {
    slug: "links-pdf",
    name: "Links no PDF",
    shortDescription: "Insira hyperlinks clicáveis em regiões do documento.",
    description: "Crie anotações Link nativas do PDF apontando para endereços HTTPS, com página e área configuráveis.",
    category: "Editar PDF",
    icon: "Layers3",
    accent: "blue",
    accept: "application/pdf,.pdf",
    multiple: false,
    keywords: ["link pdf", "hyperlink pdf", "url clicável pdf", "editar link pdf"],
    intro: "Adicione áreas clicáveis compatíveis com leitores PDF, sem transformar o link em uma simples imagem.",
    useCases: ["Adicionar site e WhatsApp", "Linkar termos e políticas", "Criar CTAs em catálogos", "Atualizar links de materiais"],
    limitations: ["A abertura do link depende das políticas do leitor PDF", "Use apenas URLs confiáveis"],
    faq: [{ question: "O link continua clicável depois do download?", answer: "Sim. A saída contém uma anotação Link nativa do formato PDF." }, privacyFaq],
  },
  {
    slug: "criar-formulario-pdf",
    name: "Criar formulário PDF",
    shortDescription: "Crie campos de texto, checkbox, rádio, lista e dropdown.",
    description: "Adicione campos AcroForm nativos a páginas existentes e gere um PDF preenchível em leitores compatíveis.",
    category: "Formulários",
    icon: "ListChecks",
    accent: "purple",
    accept: "application/pdf,.pdf",
    multiple: false,
    keywords: ["criar formulário pdf", "acroform", "campo preenchível pdf", "checkbox pdf", "dropdown pdf"],
    intro: "Transforme um PDF comum em formulário preenchível criando campos interativos sobre a página.",
    useCases: ["Ficha cadastral", "Checklist", "Formulário de RH", "Pedido e orçamento"],
    limitations: ["A aparência pode variar entre leitores PDF", "Scripts JavaScript internos e cálculos complexos não são adicionados"],
    faq: [{ question: "Os campos ficam editáveis no Adobe Reader?", answer: "Sim. São campos AcroForm nativos e leitores compatíveis podem preenchê-los." }, privacyFaq],
  },
  {
    slug: "bookmarks-pdf",
    name: "Marcadores PDF",
    shortDescription: "Crie bookmarks para navegar entre páginas.",
    description: "Monte uma árvore simples de marcadores nativos no painel de navegação do PDF.",
    category: "Organizar PDF",
    icon: "BookOpen",
    accent: "orange",
    accept: "application/pdf,.pdf",
    multiple: false,
    keywords: ["bookmark pdf", "marcadores pdf", "sumário pdf", "outline pdf"],
    intro: "Crie atalhos de navegação por título e página para documentos extensos.",
    useCases: ["Apostilas", "Contratos", "Relatórios", "Manuais técnicos"],
    limitations: ["Esta versão cria marcadores de primeiro nível", "O comportamento visual depende do leitor PDF"],
    faq: [{ question: "O marcador aparece no painel lateral do leitor?", answer: "Sim, em leitores que exibem o Outline/Bookmarks do PDF." }, privacyFaq],
  },
  {
    slug: "comparar-pdfs",
    name: "Comparar PDFs",
    shortDescription: "Compare dois documentos e destaque diferenças visuais.",
    description: "Renderize dois PDFs página a página, calcule diferenças de pixels e gere um relatório visual lado a lado com mapa de alterações.",
    category: "Organizar PDF",
    icon: "Layers3",
    accent: "rose",
    accept: "application/pdf,.pdf",
    multiple: true,
    keywords: ["comparar pdf", "diferenças pdf", "diff pdf", "revisar versões pdf"],
    intro: "Confira versões de contratos, artes e documentos com um relatório visual de diferenças.",
    useCases: ["Comparar contrato revisado", "Conferir prova gráfica", "Detectar mudança de layout", "Auditar versões"],
    limitations: ["A comparação visual considera pixels e pode marcar pequenas mudanças de renderização", "Documentos com páginas muito diferentes podem produzir áreas extensas de diferença"],
    faq: [{ question: "Compara texto também?", answer: "O relatório principal é visual e detecta qualquer mudança renderizada, inclusive texto, imagens e posicionamento." }, privacyFaq],
  },
  {
    slug: "reparar-pdf",
    name: "Reparar PDF",
    shortDescription: "Reconstrua PDFs que ainda podem ser lidos parcialmente.",
    description: "Tente normalizar a estrutura com pdf-lib e, quando necessário, reconstrua páginas renderizáveis como um novo PDF rasterizado.",
    category: "Otimizar e proteger",
    icon: "Eraser",
    accent: "green",
    accept: "application/pdf,.pdf",
    multiple: false,
    keywords: ["reparar pdf", "corrigir pdf corrompido", "recuperar pdf", "pdf inválido"],
    intro: "Recupere documentos com estrutura problemática quando ao menos um dos motores locais consegue interpretar suas páginas.",
    useCases: ["Normalizar PDF gerado por sistema antigo", "Recuperar páginas visualmente legíveis", "Regravar estrutura do arquivo", "Preparar documento para outras ferramentas"],
    limitations: ["Não é possível recuperar bytes que não existem mais no arquivo", "O modo de reconstrução visual transforma as páginas recuperadas em imagens"],
    faq: [{ question: "Recupera qualquer PDF corrompido?", answer: "Não. A ferramenta tenta duas estratégias reais de recuperação, mas arquivos severamente truncados podem não conter dados suficientes." }, privacyFaq],
  },
  {
    slug: "pdf-a",
    name: "PDF/A",
    shortDescription: "Prepare documentos para arquivamento PDF/A e verifique restrições básicas.",
    description: "Normalize metadados, XMP, formulários e recursos incompatíveis conhecidos, gerando uma cópia preparada para fluxo PDF/A com relatório de pré-validação.",
    category: "Otimizar e proteger",
    icon: "FileOutput",
    accent: "teal",
    accept: "application/pdf,.pdf",
    multiple: false,
    keywords: ["pdf a", "pdf/a", "arquivamento pdf", "pdfa 2b", "iso 19005"],
    intro: "Prepare documentos para arquivamento de longo prazo e receba um relatório local das condições que o navegador consegue verificar.",
    useCases: ["Arquivo documental", "Processos internos", "Preservação de relatórios", "Preparação para repositórios PDF/A"],
    limitations: ["Conformidade normativa definitiva deve ser confirmada por um validador PDF/A dedicado", "Perfis ICC, fontes e objetos internos do documento de origem podem exigir correção adicional para certificação estrita"],
    faq: [{ question: "O LIM PDF emite certificado de conformidade PDF/A?", answer: "Não. Ele prepara e pré-valida o documento localmente. Para comprovação normativa, valide o resultado em uma ferramenta especializada de conformidade ISO 19005." }, privacyFaq],
  },
  {
    slug: "pdf-para-powerpoint",
    name: "PDF para PowerPoint",
    shortDescription: "Converta cada página do PDF em um slide PPTX de alta fidelidade visual.",
    description: "Renderize as páginas e monte um arquivo PPTX OOXML com um slide por página, preservando a aparência do PDF.",
    category: "Converter de PDF",
    icon: "FileOutput",
    accent: "orange",
    accept: "application/pdf,.pdf",
    multiple: false,
    keywords: ["pdf para powerpoint", "pdf para pptx", "converter pdf slides"],
    intro: "Crie uma apresentação PowerPoint visualmente fiel ao PDF, com cada página posicionada como imagem em um slide.",
    useCases: ["Apresentar material existente", "Levar catálogo para PowerPoint", "Projetar apostila", "Reaproveitar PDF em reunião"],
    limitations: ["O conteúdo visual do slide é preservado como imagem", "Objetos originais do PDF não viram automaticamente formas editáveis do PowerPoint"],
    faq: [{ question: "O PPTX abre no PowerPoint?", answer: "Sim. A ferramenta gera um pacote OOXML com um slide para cada página do PDF." }, privacyFaq],
  },
  {
    slug: "powerpoint-para-pdf",
    name: "PowerPoint para PDF",
    shortDescription: "Converta PPTX em PDF com reconstrução local de slides.",
    description: "Leia slides OOXML, extraia imagens e texto e gere páginas PDF. Arquivos criados pelo conversor PDF→PowerPoint retornam com alta fidelidade visual.",
    category: "Converter para PDF",
    icon: "FilePlus2",
    accent: "orange",
    accept: ".pptx,application/vnd.openxmlformats-officedocument.presentationml.presentation",
    multiple: false,
    keywords: ["powerpoint para pdf", "pptx para pdf", "converter slides pdf"],
    intro: "Converta apresentações PPTX sem instalar PowerPoint. Slides simples e apresentações geradas pelo próprio LIM PDF são reconstruídos diretamente no navegador.",
    useCases: ["Compartilhar apresentação", "Gerar versão de impressão", "Arquivar slides", "Converter PPTX criado pelo LIM PDF"],
    limitations: ["Animações, vídeos, SmartArt e efeitos avançados não são executados pelo navegador", "Apresentações complexas podem precisar de ajustes de fidelidade"],
    faq: [{ question: "Animações aparecem no PDF?", answer: "Não. PDF é estático; a ferramenta usa o estado visual disponível no conteúdo do PPTX." }, privacyFaq],
  },
  {
    slug: "extrair-imagens-pdf",
    name: "Extrair imagens do PDF",
    shortDescription: "Extraia imagens incorporadas às páginas e baixe em ZIP.",
    description: "Analise os operadores de desenho do PDF.js e exporte imagens raster incorporadas que o navegador consegue resolver.",
    category: "Converter de PDF",
    icon: "Images",
    accent: "blue",
    accept: "application/pdf,.pdf",
    multiple: false,
    keywords: ["extrair imagens pdf", "salvar imagens pdf", "imagens incorporadas pdf"],
    intro: "Recupere fotos e imagens raster do documento sem precisar capturar a página inteira.",
    useCases: ["Extrair fotos de catálogo", "Recuperar imagens de relatório", "Separar material gráfico", "Reaproveitar imagens incorporadas"],
    limitations: ["Vetores e elementos desenhados por comandos gráficos não são imagens raster incorporadas", "Alguns formatos internos muito específicos podem ser renderizados pela página sem exposição individual pelo PDF.js"],
    faq: [{ question: "É diferente de PDF para JPG?", answer: "Sim. PDF para JPG renderiza a página inteira; esta ferramenta tenta retirar as imagens raster incorporadas no conteúdo." }, privacyFaq],
  },
  {
    slug: "limpar-documento-digitalizado",
    name: "Limpar digitalização",
    shortDescription: "Endireite, aumente contraste, clareie fundo e remova páginas em branco.",
    description: "Aplique processamento de imagem local em cada página, estimativa de inclinação, limpeza de fundo e reconstrução do PDF.",
    category: "Otimizar e proteger",
    icon: "CircleOff",
    accent: "purple",
    accept: "application/pdf,.pdf",
    multiple: false,
    keywords: ["limpar pdf escaneado", "deskew pdf", "endireitar scan", "remover fundo pdf", "página em branco"],
    intro: "Melhore digitalizações tortas ou acinzentadas antes do OCR, impressão ou arquivamento.",
    useCases: ["Recibos fotografados", "Contratos escaneados", "Apostilas antigas", "Digitalização com fundo cinza"],
    limitations: ["O processamento reconstrói as páginas como imagens", "Inclinações muito grandes ou documentos fotográficos podem precisar de ajuste manual"],
    faq: [{ question: "A ferramenta remove páginas em branco?", answer: "Sim, quando a opção estiver ativa e a página tiver densidade de conteúdo abaixo do limiar configurado." }, privacyFaq],
  },
  {
    slug: "otimizar-pdf-avancado",
    name: "Otimizar PDF avançado",
    shortDescription: "Escolha otimização estrutural ou compressão visual agressiva.",
    description: "Remova metadados, achate formulários e regrave a estrutura ou rasterize páginas com resolução e qualidade controladas para reduzir tamanho.",
    category: "Otimizar e proteger",
    icon: "Minimize2",
    accent: "green",
    accept: "application/pdf,.pdf",
    multiple: false,
    keywords: ["otimizar pdf", "compressão avançada pdf", "reduzir pdf", "fast web pdf"],
    intro: "Tenha controle sobre o equilíbrio entre fidelidade, pesquisabilidade e tamanho do arquivo final.",
    useCases: ["E-mail", "Portal com limite de upload", "Arquivo visual", "Remover dados desnecessários"],
    limitations: ["O modo visual agressivo transforma as páginas em imagens", "A redução final depende do conteúdo do PDF original"],
    faq: [{ question: "Qual modo preserva texto selecionável?", answer: "Use o modo estrutural. O modo visual oferece maior redução, mas rasteriza as páginas." }, privacyFaq],
  },
  {
    slug: "anotacoes-pdf",
    name: "Anotações PDF nativas",
    shortDescription: "Adicione notas, destaques e anotações reconhecidas por leitores PDF.",
    description: "Crie objetos de anotação PDF reais, em vez de apenas desenhar comentários sobre a página.",
    category: "Editar PDF",
    icon: "Type",
    accent: "orange",
    accept: "application/pdf,.pdf",
    multiple: false,
    keywords: ["anotação pdf", "comentário pdf", "nota pdf", "highlight annotation"],
    intro: "Inclua comentários que leitores compatíveis reconhecem como anotações interativas do documento.",
    useCases: ["Revisão de contrato", "Feedback", "Notas de estudo", "Comentários de aprovação"],
    limitations: ["A aparência e os ícones variam entre leitores", "Alguns navegadores exibem menos recursos de anotação que leitores dedicados"],
    faq: [{ question: "É uma anotação PDF de verdade?", answer: "Sim. A saída usa objetos Annot nativos com subtipo Text ou Highlight." }, privacyFaq],
  },
  {
    slug: "processamento-lote-pdf",
    name: "Processamento em lote",
    shortDescription: "Aplique a mesma operação a vários PDFs e baixe um ZIP.",
    description: "Processe vários documentos de uma vez com remoção de metadados, numeração, marca visual ou otimização estrutural.",
    category: "Organizar PDF",
    icon: "Files",
    accent: "teal",
    accept: "application/pdf,.pdf",
    multiple: true,
    keywords: ["pdf em lote", "batch pdf", "processar vários pdf", "zip pdf"],
    intro: "Economize tempo aplicando a mesma transformação em uma fila de documentos, tudo localmente.",
    useCases: ["Padronizar documentos", "Remover metadados em massa", "Numerar arquivos", "Preparar lote para envio"],
    limitations: ["O consumo de memória cresce com o tamanho e a quantidade de arquivos", "O navegador processa os documentos sequencialmente para evitar picos de memória"],
    faq: [{ question: "Recebo um arquivo por documento?", answer: "Sim. Cada PDF é processado separadamente e todos os resultados são agrupados em um ZIP." }, privacyFaq],
  },
  {
    slug: "numeracao-bates",
    name: "Numeração Bates",
    shortDescription: "Aplique prefixo e sequência jurídica em todas as páginas.",
    description: "Adicione identificadores Bates com prefixo, número inicial, quantidade de dígitos e posição configuráveis.",
    category: "Organizar PDF",
    icon: "ListOrdered",
    accent: "rose",
    accept: "application/pdf,.pdf",
    multiple: false,
    keywords: ["bates pdf", "numeração jurídica", "numerar processo pdf", "bates numbering"],
    intro: "Identifique páginas de processos, auditorias e dossiês com uma sequência estável e legível.",
    useCases: ["Processos jurídicos", "Auditoria", "Dossiês", "Controle documental"],
    limitations: ["A sequência é aplicada na ordem atual das páginas", "Planeje o prefixo e número inicial antes de combinar lotes diferentes"],
    faq: [{ question: "Posso começar em 000500?", answer: "Sim. Informe 500 como número inicial e 6 como quantidade de dígitos." }, privacyFaq],
  },
  {
    slug: "editar-metadados-pdf",
    name: "Editar metadados PDF",
    shortDescription: "Edite título, autor, assunto, palavras-chave e produtor.",
    description: "Visualize os metadados básicos disponíveis e gere uma cópia com novos valores de propriedades do documento.",
    category: "Editar PDF",
    icon: "SquarePen",
    accent: "teal",
    accept: "application/pdf,.pdf",
    multiple: false,
    keywords: ["editar metadados pdf", "autor pdf", "título pdf", "keywords pdf", "xmp pdf"],
    intro: "Atualize a identificação interna do documento sem alterar o conteúdo visual das páginas.",
    useCases: ["Organizar acervo", "Corrigir autor", "Definir assunto", "Adicionar palavras-chave"],
    limitations: ["Metadados proprietários de aplicativos específicos podem não ser preservados", "Datas e propriedades internas podem ser normalizadas ao salvar"],
    faq: [{ question: "Isso altera o texto das páginas?", answer: "Não. A ferramenta modifica somente propriedades internas do documento." }, privacyFaq],
  },
];
