import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Cpu, FileCheck2, ShieldCheck } from "lucide-react";

export const metadata: Metadata = { title: "Sobre o LIM PDF", description: "Conheça a proposta, os princípios de privacidade e a forma como as ferramentas do LIM PDF funcionam.", alternates: { canonical: "/sobre" } };

export default function AboutPage() {
  return <section className="about-page"><header><span>Sobre o LIM PDF</span><h1>Ferramentas de PDF feitas para resolver o trabalho primeiro.</h1><p>O LIM PDF é uma suíte web gratuita para editar, converter, organizar, reconhecer, proteger e revisar documentos. O projeto prioriza uma interface direta e processamento local sempre que a função permite.</p></header><div className="about-values"><article><ShieldCheck size={22} /><strong>Privacidade por arquitetura</strong><p>As ferramentas publicadas como locais processam o documento no próprio navegador. Não usamos o conteúdo do PDF para publicidade.</p></article><article><Cpu size={22} /><strong>Funções que fazem trabalho real</strong><p>Recursos são descritos com suas limitações. Quando uma etapa exige infraestrutura externa ou validação especializada, isso é informado em vez de simular suporte.</p></article><article><FileCheck2 size={22} /><strong>Resultado revisável</strong><p>O produto oferece OCR, preflight, relatórios e ferramentas complementares para ajudar a conferir o arquivo antes de compartilhar ou arquivar.</p></article></div><section className="about-detail"><h2>Por que existe</h2><p>Operações simples em PDF ainda costumam exigir programas grandes, cadastro ou envio do documento a serviços remotos. O LIM PDF reúne esses fluxos em uma experiência única, incluindo recursos básicos e profissionais, sem esconder a ferramenta principal atrás de conteúdo promocional.</p><h2>Como o serviço se mantém</h2><p>O site pode exibir publicidade quando o visitante autoriza os recursos opcionais e quando o serviço de anúncios está habilitado. Anúncios não substituem botões da ferramenta e não recebem o conteúdo dos documentos processados localmente.</p><h2>Contato e políticas</h2><p>Informações sobre dados, cookies, segurança, acessibilidade e termos estão disponíveis nas páginas institucionais do rodapé.</p><Link className="primary-button" href="/ferramentas">Abrir ferramentas <ArrowRight size={15} /></Link></section></section>;
}
