import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Sobre o LIM PDF — editor e ferramentas PDF no navegador",
  description: "Entenda como o LIM PDF trabalha, por que prioriza processamento local e quais limites o serviço informa de forma transparente.",
  alternates: { canonical: "/sobre" },
};

export default function AboutPage() {
  return <main className="institution-page about-institution"><header className="institution-hero about-hero"><span>Sobre o LIM PDF</span><h1>Um utilitário de PDF que tenta tirar etapas do caminho.</h1><p>O LIM PDF nasceu para concentrar operações que normalmente ficam espalhadas em vários sites ou programas: editar, converter, organizar, proteger, assinar e preparar documentos.</p><div className="institution-actions"><Link className="reference-primary-button" href="/ferramentas">Abrir ferramentas</Link><Link className="reference-ghost-button" href="/ferramentas/editar-pdf">Abrir editor</Link></div></header><section className="about-principles"><article><span>01</span><h2>Arquivo primeiro</h2><p>A interface é desenhada para você chegar ao upload e à ação principal sem atravessar páginas de cadastro, planos ou telas promocionais.</p></article><article><span>02</span><h2>Processamento local quando possível</h2><p>As ferramentas marcadas como locais trabalham no próprio navegador. Isso reduz envio de documentos para servidores e permite explicar com clareza o que acontece com o arquivo.</p></article><article><span>03</span><h2>Limites explícitos</h2><p>OCR pode errar caracteres. Conversão Office pode precisar de revisão. Permissões PDF dependem do leitor. O produto deve informar isso em vez de prometer fidelidade que não consegue garantir.</p></article></section><section className="about-story"><div><span>Como evoluímos</span><h2>O editor é o centro do produto.</h2></div><p>As ferramentas menores resolvem tarefas rápidas. O Editar PDF reúne criação visual, texto, imagens, assinatura, redação segura, páginas, camadas, localização e um modo preciso para alterações mais controladas. A partir dele, atalhos levam para OCR, dimensionamento, recorte, proteção e compactação.</p><p>O objetivo não é imitar a quantidade de botões de um software desktop. É oferecer as funções mais usadas de forma visível e manter opções avançadas perto do contexto em que fazem sentido.</p></section><section className="about-transparency"><div><h2>Publicidade e privacidade</h2><p>O site pode usar publicidade para manter o acesso gratuito. Anúncios não devem parecer botões de selecionar arquivo, converter ou baixar. O conteúdo do PDF processado localmente não é usado pelo LIM PDF para personalizar publicidade.</p></div><div><h2>Quem atende</h2><p>Falhas, sugestões, privacidade, segurança e abuso podem ser encaminhados pela página de contato. O canal informa exatamente para onde a mensagem será enviada, sem formulário que finge funcionar quando não existe integração configurada.</p><Link href="/contato">Ir para contato →</Link></div></section></main>;
}
