declare module "lucide-react" {
  import type { ComponentType, SVGProps } from "react";

  export type LucideProps = SVGProps<SVGSVGElement> & {
    size?: string | number;
    strokeWidth?: string | number;
    absoluteStrokeWidth?: boolean;
  };

  export type LucideIcon = ComponentType<LucideProps>;

  export const AlertCircle: LucideIcon;
  export const ArrowDown: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowUp: LucideIcon;
  export const BookOpen: LucideIcon;
  export const CalendarDays: LucideIcon;
  export const Check: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const CircleOff: LucideIcon;
  export const Clock3: LucideIcon;
  export const Clipboard: LucideIcon;
  export const Command: LucideIcon;
  export const Contact: LucideIcon;
  export const Cookie: LucideIcon;
  export const CopyPlus: LucideIcon;
  export const Crop: LucideIcon;
  export const Download: LucideIcon;
  export const Eraser: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const FileImage: LucideIcon;
  export const FileMinus: LucideIcon;
  export const FileOutput: LucideIcon;
  export const FilePlus2: LucideIcon;
  export const FileQuestion: LucideIcon;
  export const FileStack: LucideIcon;
  export const FileText: LucideIcon;
  export const Files: LucideIcon;
  export const FlipHorizontal2: LucideIcon;
  export const Globe2: LucideIcon;
  export const Grid2X2: LucideIcon;
  export const HardDrive: LucideIcon;
  export const Image: LucideIcon;
  export const ImagePlus: LucideIcon;
  export const Images: LucideIcon;
  export const Info: LucideIcon;
  export const Languages: LucideIcon;
  export const Layers3: LucideIcon;
  export const LayoutGrid: LucideIcon;
  export const ListChecks: LucideIcon;
  export const ListOrdered: LucideIcon;
  export const ListRestart: LucideIcon;
  export const LoaderCircle: LucideIcon;
  export const LockKeyhole: LucideIcon;
  export const Menu: LucideIcon;
  export const Minimize2: LucideIcon;
  export const MousePointer2: LucideIcon;
  export const PaintBucket: LucideIcon;
  export const PanelTop: LucideIcon;
  export const PencilLine: LucideIcon;
  export const Repeat2: LucideIcon;
  export const RotateCw: LucideIcon;
  export const Save: LucideIcon;
  export const Scaling: LucideIcon;
  export const Search: LucideIcon;
  export const Send: LucideIcon;
  export const Settings2: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const Shuffle: LucideIcon;
  export const Signature: LucideIcon;
  export const SlidersHorizontal: LucideIcon;
  export const Sparkles: LucideIcon;
  export const SplitSquareVertical: LucideIcon;
  export const SquarePen: LucideIcon;
  export const Star: LucideIcon;
  export const Stamp: LucideIcon;
  export const TableProperties: LucideIcon;
  export const TextSearch: LucideIcon;
  export const Trash2: LucideIcon;
  export const Type: LucideIcon;
  export const Undo2: LucideIcon;
  export const Redo2: LucideIcon;
  export const UploadCloud: LucideIcon;
  export const Wrench: LucideIcon;
  export const X: LucideIcon;
}
