import {
  CircleOff,
  SquarePen,
  CopyPlus,
  Crop,
  Eraser,
  FileImage,
  FileMinus,
  FileOutput,
  FilePlus2,
  Files,
  FlipHorizontal2,
  Image,
  ImagePlus,
  Images,
  Layers3,
  LayoutGrid,
  ListChecks,
  ListOrdered,
  ListRestart,
  Minimize2,
  PaintBucket,
  PanelTop,
  RotateCw,
  Scaling,
  Shuffle,
  Signature,
  SplitSquareVertical,
  Stamp,
  TextSearch,
  Type,
} from "lucide-react";
import type { ToolDefinition } from "@/lib/tools";

const icons = {
  CircleOff,
  SquarePen,
  CopyPlus,
  Crop,
  Eraser,
  FileImage,
  FileMinus,
  FileOutput,
  FilePlus2,
  Files,
  FlipHorizontal2,
  Image,
  ImagePlus,
  Images,
  Layers3,
  LayoutGrid,
  ListChecks,
  ListOrdered,
  ListRestart,
  Minimize2,
  PaintBucket,
  PanelTop,
  RotateCw,
  Scaling,
  Shuffle,
  Signature,
  SplitSquareVertical,
  Stamp,
  TextSearch,
  Type,
};

export function ToolIcon({ icon }: Pick<ToolDefinition, "icon">) {
  const Icon = icons[icon];
  return <Icon size={24} strokeWidth={1.9} aria-hidden="true" />;
}
