import { chromium } from 'playwright-core';
import fs from 'node:fs';
const browser = await chromium.launch({headless:true, executablePath:'/usr/bin/chromium', args:['--no-sandbox']});
const page = await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];
page.on('console', msg=>{ if(msg.type()==='error') errors.push(msg.text()); });
page.on('pageerror', err=>errors.push(err.message));
await page.goto('http://172.26.36.6:3100', {waitUntil:'networkidle'});
if(!(await page.locator('h1').textContent())?.includes('Tudo que seu PDF precisa')) throw new Error('home h1 missing');
await page.screenshot({path:'/mnt/data/lim-pdf-production-desktop.png', fullPage:true});
await page.goto('http://172.26.36.6:3100/ferramentas/juntar-pdf', {waitUntil:'networkidle'});
await page.setInputFiles('input[type=file]', ['/tmp/limpdf-smoke/first.pdf','/tmp/limpdf-smoke/second.pdf']);
const downloadPromise=page.waitForEvent('download');
await page.getByRole('button',{name:'Juntar PDF agora'}).click();
const download=await downloadPromise;
await download.saveAs('/tmp/limpdf-browser-merged.pdf');
if(!fs.existsSync('/tmp/limpdf-browser-merged.pdf')) throw new Error('merge download missing');
await page.goto('http://172.26.36.6:3100/ferramentas/pdf-para-jpg', {waitUntil:'networkidle'});
await page.setInputFiles('input[type=file]', '/tmp/limpdf-smoke/first.pdf');
const imageDownloadPromise=page.waitForEvent('download');
await page.getByRole('button',{name:'PDF para JPG agora'}).click();
const imageDownload=await imageDownloadPromise;
await imageDownload.saveAs('/tmp/limpdf-browser-jpg.zip');
if(!fs.existsSync('/tmp/limpdf-browser-jpg.zip')) throw new Error('jpg zip missing');
await page.setViewportSize({width:390,height:844});
await page.goto('http://172.26.36.6:3100', {waitUntil:'networkidle'});
await page.screenshot({path:'/mnt/data/lim-pdf-production-mobile.png', fullPage:true});
console.log(JSON.stringify({ok:true, errors, merged:fs.statSync('/tmp/limpdf-browser-merged.pdf').size, jpgZip:fs.statSync('/tmp/limpdf-browser-jpg.zip').size}));
await browser.close();
